POST http://localhost:8090/sakila/store HTTP/1.1
Content-Type: text/xml


<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
     xmlns:jets="http://services.web.jets.iti.gov/">
    <soap:Body>
        <jets:getStoreById>
            <arg0>1</arg0>
        </jets:getStoreById>
    </soap:Body>
</soap:Envelope>

###
POST http://localhost:8090/sakila/store HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
     xmlns:jets="http://services.web.jets.iti.gov/">
    <soap:Body>
        <jets:getAllStores/>
    </soap:Body>
</soap:Envelope>


###
POST http://localhost:8090/sakila/store HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
     xmlns:jets="http://services.web.jets.iti.gov/">
    <soap:Body>
        <jets:deleteStore>
            <arg0>1</arg0>
        </jets:deleteStore>
    </soap:Body>
</soap:Envelope>


###
POST http://localhost:8090/sakila/store HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
     xmlns:jets="http://services.web.jets.iti.gov/">
    <soap:Body>
        <jets:addStore>
            <arg0>
                <lastUpdate>2006-02-15T04:57:12+02:00</lastUpdate>
            </arg0>
        </jets:addStore>
    </soap:Body>
</soap:Envelope>


###
POST http://localhost:8090/sakila/store HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
     xmlns:jets="http://services.web.jets.iti.gov/">
    <soap:Body>
        <jets:updateStore>
            <arg0>
                <lastUpdate>2006-02-15T04:57:12+02:00</lastUpdate>
                <storeId>2</storeId>
            </arg0>
        </jets:updateStore>
    </soap:Body>
</soap:Envelope>


###
POST http://localhost:8090/sakila/store HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
     xmlns:jets="http://services.web.jets.iti.gov/">
    <soap:Body>
        <jets:getStoreInventories>
            <arg0>1</arg0>
        </jets:getStoreInventories>
    </soap:Body>
</soap:Envelope>


###
POST http://localhost:8090/sakila/store HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
     xmlns:jets="http://services.web.jets.iti.gov/">
    <soap:Body>
        <jets:getStoreCustomers>
            <arg0>1</arg0>
        </jets:getStoreCustomers>
    </soap:Body>
</soap:Envelope>


###
POST http://localhost:8090/sakila/store HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
     xmlns:jets="http://services.web.jets.iti.gov/">
    <soap:Body>
        <jets:getStoreStaff>
            <arg0>1</arg0>
        </jets:getStoreStaff>
    </soap:Body>
</soap:Envelope>

